apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
  namespace: default 

spec:
  teamId: "postgres"
  volume:
    size: 2G
  numberOfInstances: 2
  enableShmVolume: true
  postgresql:
    version: "13"
    parameters:
      max_connections: "250"
  enableLogicalBackup: true
  logicalBackupSchedule: "* * * * *"
