apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
  namespace: default
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
    - superuser
    - createdb
    foo_user: []  # role for application foo
  enableMasterLoadBalancer: true
  enableLogicalBackup: true
#  enableConnectionPooler: true  # not needed when connectionPooler section is present (see below)
  allowedSourceRanges:
  - 0.0.0.0/0
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "12"
