apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-pod-config
  namespace: default
data:
  AWS_ACCESS_KEY_ID: "BKIKJAA5BMMU2RHO6IBB"
  AWS_SECRET_ACCESS_KEY: "V7f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12i"
  AWS_ENDPOINT: "http://185.22.98.6:32000"
  AWS_S3_FORCE_PATH_STYLE: "true"
  AWS_REGION: "us-east-1"
  USE_WALG_BACKUP: "true"
  WALG_DISABLE_S3_SSE: "true"
